* EXWM setup

This file describes how to setup a custom Xsession for using exwm.
For more info see:

https://wiki.ubuntu.com/CustomXSession
https://wiki.debian.org/Xsession

Setup a desktopfile for the display manager. This will appear in the menu.
The file should just run Xsession script which in turn will run .xsession.

/usr/share/xsessions/emacs.desktop
#+BEGIN_SRC sh
[Desktop Entry]
Type=Application
Name=EmacsWM
Comment=This runs ~/.xsession
Exec=/etc/X11/Xsession
#+END_SRC


Then setup the session script, which will be executed with above
config. Dont forget to make it executable afterwards.

~/.xsession
#+BEGIN_SRC sh
#!/usr/bin/env bash

# disable normal mouse behaviour
xinput disable "TPPS/2 IBM TrackPoint"

# basic gnome functionalty, fonts etc
gnome-settings-daemon & #

# load custom key layout
xmodmap ~/.Xmodmap


# sticky keys
xkbset sticky -twokey -latchlock
xkbset exp 1 =accessx =sticky =twokey =latchlock

# workaround for some keys
xbindkeys &

# magic
exec emacs --eval "(progn (require 'exwm) (require 'exwm-config) (defun exwm-config-ido ()) (exwm-config-default))"
#+END_SRC


Now choosing emacsWM in display manager, will start the Desktop with exwm.

To make it possible to start an ubuntu gnome-session via startx from vt (copied from
ubuntu.desktop in xsession dir:

.xinitrc
#+BEGIN_SRC sh
#!/bin/bash

env GNOME_SHELL_SESSION_MODE=ubuntu gnome-session --session=ubuntu
#+END_SRC



* Enable Hyper key

From [[https://github.com/logicbomb/linux-config][here]]:

For some reason Ubuntu treats the Hyper key the same as the Super key, they
are both assigned to Mod3. Further complicating the issue Gnome doesn't source
.xinit on startup so it's difficult to run xmodmap when a desktop session
starts. The best way I found is to modify the keyboard codes used in the X
session by modifying the xkb configuration.

NOTE Make a copy fo the file to be modified:

sudo cp /usr/share/x11/xkb/symbols/pc /usr/share/x11/xkb/symbols/pc.ORIG

We are going to change the modifier of the Super key from Mod3 to Mod4, this
leaves the Hyper assigned to Mod4 and the OS can disambiguate the 2 keys.

Open the file /usr/share/x11/xkb/symbols/pc and find all references to the
SUPER_L and SUPER_R keys being assigned to Mod4 and change it to Mod3:

Line 39: modifier_map Mod4 { Super_L, Super_R }; -> modifier_map Mod3 { Super_L, Super_R };

Line 53: modifier_map Mod4 { <SUPR> }; -> modifier_map Mod3 { <SUPR> };

NOTE The drawback to this method is that if an update or program makes a
change to the keyboard configuration file, changes are lost and need to be
reapplied.
